name: praktikum_satu
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  responsive_framework: ^0.1.4
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6
  flutter_barcode_scanner: ^2.0.0
  http: ^0.13.5
  email_validator: ^2.1.17
  shared_preferences: ^2.0.15

flutter_icons:
  android: true
  ios: true
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: San Franscisco
  #     fonts:
  #       - asset: fonts/
